### ISSUE TITLE
Não funciona no Vue 2

### ISSUE THREAD

**Issue by Beatriz-Sanchez** [vue-a11y/vue-vlibras#3]
Tentando implementar em um projeto em Vue 2. Oplugin renderiza se eu seguir a documentacão e colocar tudo no body do index.html, porém isso interfere no funcionamento do skeleton-loader do Vuetify 2.

Se tento usar o seu componente feito para Vue 2, o Widget simplesmente não renderiza. Tentei fazer várias alterações no componente, mas todas sem sucesso.

**Comment by lucasferreiralimax** [comment]
> Tentando implementar em um projeto em Vue 2. Oplugin renderiza se eu seguir a documentacão e colocar tudo no body do index.html, porém isso interfere no funcionamento do skeleton-loader do Vuetify 2.
> 
> Se tento usar o seu componente feito para Vue 2, o Widget simplesmente não renderiza. Tentei fazer várias alterações no componente, mas todas sem sucesso.

Tudo bem @Beatriz-Sanchez ?
Poderia compartilhar o package.json do projeto para eu conseguir entender as versões e tentar reproduzir o mais próximo do seu ambiente?

**Comment by lucasferreiralimax** [comment]
Consegui reproduzir o problema mencionado na issue utilizando as informações fornecidas e observei um bug relacionado ao skeleton. Gostaria de confirmar se este é o mesmo bug que você está enfrentando ou se trata de outra situação.

O único comportamento inesperado que encontrei com o Vuetify foi uma alteração na animação de carregamento do skeleton ao utilizar o VLibras.

Confira o vídeo abaixo para mais detalhes:
[Assista ao vídeo no YouTube](https://youtu.be/aM_RZ-ChICE)

**Comment by lucasferreiralimax** [comment]
@Beatriz-Sanchez Eu fiz o ajuste na biblioteca para evitar o conflito mencionado assim que for revisado será atualizada, se quiser acompanhar o [pull request keyframes css unique name](https://github.com/vue-a11y/vue-vlibras/pull/4).

**Comment by lucasferreiralimax** [comment]
@Beatriz-Sanchez, por favor, atualize seu pacote para a versão 0.1.3 - https://www.npmjs.com/package/@vue-a11y/vlibras.

A solução foi implementada. Agradeço se puder verificar as atualizações.
